artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/adi180397/Churn-Prediction/raw/refs/heads/main/ecommerce_customer_churn_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/ecommerce_customer_churn_dataset - Copy.csv
  status_file: artifacts/data_validation/schema.txt


data_transformation:
 root_dir: artifacts/data_transformation
 local_data_file: artifacts/data_ingestion/ecommerce_customer_churn_dataset - Copy.csv
 train_csv: artifacts/data_transformation/train.csv
 test_csv: artifacts/data_transformation/test.csv

